# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-16 18:09:15
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def StormBufferCreation(_Value_Reconstruct=r"E:\ArcPro\Social_and_Precautionary\testMP\StormBuffers.gdb\{Value}_Reconstruct", atlantic_storms_rejoined_atlantic_storms_rejoined="ModelBuilder\\atlantic_storms_rejoined:atlantic_storms_rejoined"):  # 4a. Storm Buffer Creation

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"d:\arcgis\Resources\ArcToolbox\toolboxes\GeoAnalytics Desktop Tools.tbx")

    for Value, Count_3_ in #  NOT  IMPLEMENTED(atlantic_storms_rejoined_atlantic_storms_rejoined.__str__().format(**locals(),**globals())if isinstance(atlantic_storms_rejoined_atlantic_storms_rejoined, str) else atlantic_storms_rejoined_atlantic_storms_rejoined, [], "", ["max_meters_34_kt", "max_meters_50_kt", "max_meters_64_kt"]):

        # Process: Reconstruct Tracks (Reconstruct Tracks) (gapro)
        arcpy.gapro.ReconstructTracks(input_layer=atlantic_storms_rejoined_atlantic_storms_rejoined.__str__().format(**locals(),**globals())if isinstance(atlantic_storms_rejoined_atlantic_storms_rejoined, str) else atlantic_storms_rejoined_atlantic_storms_rejoined, out_feature_class=_Value_Reconstruct.__str__().format(**locals(),**globals())if isinstance(_Value_Reconstruct, str) else _Value_Reconstruct, track_fields=["id"], method="GEODESIC", buffer_type="FIELD", buffer_field=Value, summary_fields=[["name", "FIRST"]])

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="MAXOF", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", maintainAttachments=True, maintainSpatialIndex=False, 
                          matchMultidimensionalVariable=True, nodata="NONE", outputMFlag="Same As Input", 
                          outputZFlag="Same As Input", preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", 
                          qualifiedFieldNames=True, randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", 
                          resamplingMethod="NEAREST", scratchWorkspace="E:\\ArcPro\\Social_and_Precautionary\\testMP\\Scratch\\scratch.gdb", terrainMemoryUsage=False, 
                          tileSize="128 128", tinSaveVersion="CURRENT", transferDomains=False, 
                          transferGDBAttributeProperties=False, unionDimension=False, workspace="E:\\ArcPro\\Social_and_Precautionary\\testMP\\testMP.gdb"):
        StormBufferCreation(*argv[1:])
