# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-04-16 18:09:29
"""
import arcpy
import os

from sys import argv
def FeatureClassGenerator(workspace, wild_card, feature_type, recursive) :
  with arcpy.EnvManager(workspace = workspace):

    dataset_list = [""]
    if recursive:
      datasets = arcpy.ListDatasets()
      dataset_list.extend(datasets)

    for dataset in dataset_list:
      featureclasses = arcpy.ListFeatureClasses(wild_card, feature_type, dataset)
      for fc in featureclasses:
        yield os.path.join(workspace, dataset, fc), fc


#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def StormCount(Waterbody_Stormcount_Waterbody_Stormcount="ModelBuilder\\Waterbody_Stormcount:Waterbody_Stormcount"):  # 5a. Storm Count

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    StormBuffers_gdb = "E:\\ArcPro\\Social_and_Precautionary\\testMP\\StormBuffers.gdb"

    for max_meters_34_kt_Reconstruct, Name in FeatureClassGenerator(StormBuffers_gdb, "", "", "NOT_RECURSIVE"):

        # Process: Add Spatial Join (Add Spatial Join) (management)
        Waterbody_Stormcount = arcpy.management.AddSpatialJoin(target_features=Waterbody_Stormcount_Waterbody_Stormcount.__str__().format(**locals(),**globals())if isinstance(Waterbody_Stormcount_Waterbody_Stormcount, str) else Waterbody_Stormcount_Waterbody_Stormcount, join_features=max_meters_34_kt_Reconstruct, field_mapping="id \"id\" true true false 8000 Text 0 0,First,#,E:\\ArcPro\\Social_and_Precautionary\\testMP\\StormBuffers.gdb\\max_meters_34_kt_Reconstruct,id,0,7999", permanent_join="PERMANENT_FIELDS")[0]

        return Waterbody_Stormcount

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(autoCommit=1000, baUseDetailedAggregation=False, cellAlignment="DEFAULT", 
                          cellSize="MAXOF", cellSizeProjectionMethod="CONVERT_UNITS", coincidentPoints="MEAN", 
                          compression="LZ77", maintainAttachments=True, maintainSpatialIndex=False, 
                          matchMultidimensionalVariable=True, nodata="NONE", outputMFlag="Same As Input", 
                          outputZFlag="Same As Input", preserveGlobalIds=False, pyramid="PYRAMIDS -1 NEAREST DEFAULT 75 NO_SKIP NO_SIPS", 
                          qualifiedFieldNames=True, randomGenerator="0 ACM599", rasterStatistics="STATISTICS 1 1", 
                          resamplingMethod="NEAREST", scratchWorkspace="E:\\ArcPro\\Social_and_Precautionary\\testMP\\Scratch\\scratch.gdb", terrainMemoryUsage=False, 
                          tileSize="128 128", tinSaveVersion="CURRENT", transferDomains=False, 
                          transferGDBAttributeProperties=False, unionDimension=False, workspace="E:\\ArcPro\\Social_and_Precautionary\\testMP\\testMP.gdb"):
        StormCount(*argv[1:])
